### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by talentlessguy** [Wallet3/Wallet3#1]
Please also ship AppImage for Linux support

**Comment by UnsignedInt8** [comment]
Thanks. Linux will be supported ASAP

**Comment by criadoperez** [comment]
Looking forward to it... until then I cant use Wallet3.

**Comment by UnsignedInt8** [comment]
We are going to release 1.9.1 this week, which is fully support Linux.

**Comment by UnsignedInt8** [comment]
v1.9.1 has been released 😉: https://github.com/Wallet3/Wallet3/releases/download/v1.9.1/wallet3-linux-x86_64-1.9.1.AppImage
