### ISSUE TITLE
BSC-testnet

### ISSUE THREAD

**Issue by iower** [Wallet3/Wallet3#2]
Hi, great wallet!
It would be helpful for developers to be able to switch to BSC-testnet.

![image](https://user-images.githubusercontent.com/35522011/147326644-01ce614f-ab84-4f05-8ca3-38b9b1820605.png)
---
```
RPC URL: https://data-seed-prebsc-1-s1.binance.org:8545/
ChainID: 97
Symbol: BNB
Block Explorer URL: https://testnet.bscscan.com
```

**Comment by UnsignedInt8** [comment]
Thanks. Will be added in the next update

**Comment by UnsignedInt8** [comment]
Added in v1.9.2 😎 https://github.com/Wallet3/Wallet3/releases/tag/v1.9.2
